### ISSUE TITLE
Form to slack

### ISSUE THREAD

**Issue by rickprince** [sjelfull/Craft-Slack#1]
Could craft send the message to slack if a front end user submits a contact form - if so, how?

Thanks heaps, this could be really handy!

**Comment by sjelfull** [comment]
Sorry for being slow to reply - I was still in vacation mode!

Yes, technically, you can use the Slack plugin service to send the message. It doesn't currently listen to any hooks, but you might add it manually to the P&T ContactForm plugin (if using that).

[See line 54 in ContactFormService](https://github.com/pixelandtonic/ContactForm/blob/master/contactform/services/ContactFormService.php#L54)

Right after that line, you can for example do something like this:

``` php
$slackMessage = array(
    'E-mail received with subject: ' . $email->subject,
    'Messages reads as following:' . $email->body 
);
craft()->slack->sendMessage(implode(' - ', $slackmessage ));
```
